server:
  port: 19000
eureka:
  instance:
    hostname: "eurekaServer19000"
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: "http://eurekaServer19001:19001/eureka/"
  server:
    enable-self-preservation: false