server:
  port: 19001
eureka:
  instance:
    hostname: "eurekaServer19001"
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url:
      defaultZone: "http://eurekaServer19000:19000/eureka/"
  server:
    enable-self-preservation: false